version: 0.2

phases:
  build:
    commands:
      - echo "Building the application..."
      - mkdir -p build
      - cp -R src/* build/
      - cp appspec.yml build/
      - cp -R scripts build/
artifacts:
  files:
    - '**/*'
  base-directory: build
